[package]
name = "swc_plugin_remove_side_effect"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1"
fxhash= "0.2.1"
easy-error = "1.0.0"
tracing = { version="0.1.34", features = ["release_max_level_info"] }
swc_core = {version = "0.79.56", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
  "ecma_codegen",
]}
swc_common = { version = "0.31.18", features = ["concurrent"] }
serde_json = {version = "1", features = ["unbounded_depth"]}

[dev-dependencies]
testing = "0.33.21"
